default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-case-conflict
    -   id: detect-private-key
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
    -   id: ruff
    -   id: ruff-format
