# Generated by Django 5.1.1 on 2024-09-27 07:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type_person', models.CharField(choices=[('NP', 'Natural Person'), ('LE', 'Legal Entity')], default='NP', max_length=2, verbose_name='Type of Person')),
                ('type_service', models.CharField(choices=[('OA', 'Only Alarms'), ('OC', 'Only Cameras'), ('AC', 'Alarms and Cameras')], default='AC', max_length=2, verbose_name='Type of Service')),
                ('query', models.TextField(verbose_name='query')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zp.address', verbose_name='Adress')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='customers_p_name_47673a_idx'), models.Index(fields=['query'], name='customers_p_query_c7781c_idx')],
            },
        ),
    ]
