# Generated by Django 5.1.1 on 2024-10-02 20:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("alarms", "Only Alarms"),
                            ("cameras", "Only Cameras"),
                            ("alarms_and_cameras", "Alarms and Cameras"),
                        ],
                        default="alarms_and_cameras",
                        max_length=18,
                        verbose_name="Service Type",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ("name",),
            },
        ),
    ]
