# Generated by Django 5.1.1 on 2024-10-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Alarms", "Only Alarms"),
                    ("Cameras", "Only Cameras"),
                    ("Alarms and cameras", "Alarms and Cameras"),
                ],
                default="Alarms and cameras",
                max_length=18,
                verbose_name="Service Type",
            ),
        ),
    ]
