[tool.poetry]
name = "zona-protegida"
version = "0.1.0"
description = ""
authors = ["Danilo Marto de Carvalho <dmcarvalho@tutanota.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
