# Generated by Django 5.1.1 on 2024-10-05 03:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0002_customer_address_alter_customer_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField(default="general", max_length=255, verbose_name="Description")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm",
                "verbose_name_plural": "Alarms",
                "ordering": ("description",),
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField(default="general", max_length=255, verbose_name="Description")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "camera",
                "verbose_name_plural": "cameras",
                "ordering": ("description",),
            },
        ),
    ]
