# Generated by Django 5.1.1 on 2024-10-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='mac',
            field=models.CharField(blank=True, max_length=32, verbose_name='MAC'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='password_master',
            field=models.CharField(blank=True, max_length=12, verbose_name='Password Master'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='camera',
            name='serial',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
